### ISSUE TITLE
Current release/build not working

### ISSUE THREAD

**Issue by Zauberfisch** [joelmukuthu/animated-scroll#40]
The current build in `dist/` is not working. It would appear that `src/` has received some fixes since the last build (or perhaps an automated build is failing?).

See for example: [dist/AnimatedScroll.js#L163](https://github.com/joelmukuthu/animated-scroll/blob/master/dist/AnimatedScroll.js#L163) vs [src/AnimatedScroll.js#L64](https://github.com/joelmukuthu/animated-scroll/blob/master/src/AnimatedScroll.js#L64)

In my project I was able to use this package by importing `import AnimatedScroll from "animated-scroll/src/AnimatedScroll.js"` rather than from dist.
So I guess a simple rebuild & re-release should fix this.

**Comment by joelmukuthu** [comment]
Hi @Zauberfisch, thank you for reporting this and taking a look into #21. I'll be a bit busy for some days but I'll look into this towards the end of the week, but if you have some time to send a PR that's very welcome. Thanks again, Joel.

**Comment by Zauberfisch** [comment]
I've created a PR for the `animationProperty` thing. 

I'm also happy to run the build script and create a PR for that, but I figured as package maintainer and trusted source it might be better that you are the one creating the minified version of this software.

**Comment by joelmukuthu** [comment]
You're quite right. From the failed CI build in your PR, it looks like I'll need to update some dependencies. I'll set aside some time for that later in the week. Much obliged.

**Comment by joelmukuthu** [comment]
I published v0.0.3. @Zauberfisch let me know if the new build works if you have time. Many thanks.

**Comment by Zauberfisch** [comment]
@joelmukuthu didn't test it thoroughly, but appears to be working. thank you.
